-- Kastriva Smart Kasir - production-ready data model starter
create extension if not exists pgcrypto;
create table if not exists stores (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, phone text, address text, tax_rate numeric default 0, service_rate numeric default 0, created_at timestamptz default now());
create table if not exists tables (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, code text not null, seats int default 2, status text default 'AVAILABLE', unique(store_id,code));
create table if not exists categories (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, name text not null, sort_order int default 0);
create table if not exists menu_items (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, category_id uuid references categories(id), name text not null, description text, price numeric not null, cost numeric default 0, stock numeric default 0, active boolean default true, image_url text, created_at timestamptz default now());
create table if not exists orders (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, table_id uuid references tables(id), customer_name text, channel text not null, status text not null default 'NEW', subtotal numeric default 0, discount numeric default 0, tax numeric default 0, service numeric default 0, total numeric default 0, note text, created_at timestamptz default now());
create table if not exists order_items (id uuid primary key default gen_random_uuid(), order_id uuid references orders(id) on delete cascade, menu_item_id uuid references menu_items(id), name_snapshot text not null, price numeric not null, qty numeric not null, note text);
create table if not exists reservations (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, guest_name text not null, phone text, party_size int not null, reserved_at timestamptz not null, status text default 'BOOKED', note text);
create table if not exists customers (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, name text not null, phone text, email text, tier text default 'MEMBER', visits int default 0, total_spend numeric default 0, preferences jsonb default '{}'::jsonb);
create table if not exists inventory_items (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, name text not null, unit text default 'unit', stock numeric default 0, par_level numeric default 0, cost numeric default 0);
create index if not exists orders_store_created_idx on orders(store_id,created_at desc);
create index if not exists menu_store_active_idx on menu_items(store_id,active);