 "use client";
import {useMemo,useState} from "react";
import {BarChart3, Bell, BookOpen, CalendarDays, ChefHat, ChevronRight, CircleDollarSign, ClipboardList, Coffee, Grid2X2, LayoutDashboard, LogOut, Menu as MenuIcon, Package, QrCode, ReceiptText, Search, Settings, ShoppingCart, Sparkles, Store, Users, X} from "lucide-react";
import {initialOrders,menus,rupiah,tables,nowTime,Order,Menu} from "@/lib/data";

const nav=[
["Dashboard",LayoutDashboard],["POS",ShoppingCart],["Pesanan",ClipboardList],["Dapur",ChefHat],["Meja",Grid2X2],["Reservasi",CalendarDays],["Menu",BookOpen],["Inventory",Package],["Pelanggan",Users],["Staff",Users],["Laporan",BarChart3],["QR & Online",QrCode],["Pengaturan",Settings]
] as const;

export default function AdminApp(){
 const [page,setPage]=useState("Dashboard"); const [open,setOpen]=useState(false); const [orders,setOrders]=useState<Order[]>(initialOrders); const [cart,setCart]=useState<{item:Menu;qty:number}[]>([]); const [cat,setCat]=useState("All"); const [query,setQuery]=useState(""); const [toast,setToast]=useState("");
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const add=(item:Menu)=>setCart(c=>{const x=c.find(i=>i.item.id===item.id);return x?c.map(i=>i.item.id===item.id?{...i,qty:i.qty+1}:i):[...c,{item,qty:1}]});
 const total=cart.reduce((s,i)=>s+i.item.price*i.qty,0);
 const updateStatus=(id:string,status:Order["status"])=>setOrders(os=>os.map(o=>o.id===id?{...o,status}:o));
 const categories=["All",...Array.from(new Set(menus.map(m=>m.category)))];
 const filtered=menus.filter(m=>(cat==="All"||m.category===cat)&&m.name.toLowerCase().includes(query.toLowerCase()));
 const completeSale=()=>{if(!cart.length)return notify("Keranjang kosong");const order:Order={id:`ORD-${Date.now().toString().slice(-4)}`,table:"Counter",customer:"Walk-in",status:"PAID",total,items:cart.map(x=>`${x.item.name} x${x.qty}`),time:nowTime(),channel:"POS"};setOrders(o=>[order,...o]);setCart([]);notify("Transaksi berhasil disimpan")};
 const render=()=>{
  if(page==="POS")return <PosPage filtered={filtered} categories={categories} cat={cat} setCat={setCat} query={query} setQuery={setQuery} add={add} cart={cart} setCart={setCart} total={total} completeSale={completeSale}/>;
  if(page==="Pesanan")return <OrdersPage orders={orders} updateStatus={updateStatus}/>;
  if(page==="Dapur")return <KitchenPage orders={orders} updateStatus={updateStatus}/>;
  if(page==="Meja")return <TablesPage/>;
  if(page==="Reservasi")return <SimplePage title="Reservasi & Booking" icon={<CalendarDays/>} desc="Kelola booking, deposit, guest note, seating preference dan waiting list." rows={["RSV-901 • 19:00 • 4 pax • VIP","RSV-902 • 19:30 • 2 pax • Window","RSV-903 • 20:00 • 6 pax • Birthday"]}/>;
  if(page==="Menu")return <MenuPage/>;
  if(page==="Inventory")return <InventoryPage/>;
  if(page==="Pelanggan")return <SimplePage title="CRM Pelanggan" icon={<Users/>} desc="Profil tamu, visit history, loyalty, preferences dan birthday reminder." rows={["Budi Santoso • 14 visits • Gold","Sari Wijaya • 8 visits • Silver","Andi Pratama • 5 visits • Member"]}/>;
  if(page==="Staff")return <SimplePage title="Staff & Shift" icon={<Users/>} desc="Role-based access, shift, attendance, cashier accountability." rows={["Ayu • Manager • On duty","Rizky • Cashier • On duty","Dimas • Kitchen • On duty"]}/>;
  if(page==="Laporan")return <ReportsPage orders={orders}/>;
  if(page==="QR & Online")return <OnlinePage/>;
  if(page==="Pengaturan")return <SettingsPage/>;
  return <Dashboard orders={orders} setPage={setPage}/>;
 };
 return <div className="app"><aside className={`sidebar glass ${open?"open":""}`}><div className="brand"><img src="/brand/logo.png" alt="Kastriva"/><div><b>KASTRIVA SMART</b><small>Enterprise POS</small></div></div><nav className="nav">{nav.map(([label,Icon])=><button key={label} className={page===label?"active":""} onClick={()=>{setPage(label);setOpen(false)}}><Icon size={17}/>{label}</button>)}</nav><div className="sidebarBottom"><button className="nav" style={{width:"100%",border:0,background:"transparent",color:"#b8cadb",padding:"11px 12px"}}><LogOut size={17}/>Logout</button></div></aside><div className={`overlay ${open?"show":""}`} onClick={()=>setOpen(false)}/><main className="main"><header className="topbar"><button className="iconBtn mobileMenu" onClick={()=>setOpen(true)}><MenuIcon size={20}/></button><div className="pageTitle"><h1>{page}</h1><p>Kastriva Grand Dining • {new Date().toLocaleDateString("id-ID",{weekday:"long",day:"2-digit",month:"long"})}</p></div><div className="topActions"><button className="iconBtn"><Bell size={18}/></button><button className="btn primary hideSm" onClick={()=>setPage("POS")}><ShoppingCart size={16}/> New Order</button></div></header>{render()}</main>{toast&&<div className="toast">{toast}</div>}</div>
}

function Dashboard({orders,setPage}:{orders:Order[];setPage:(s:string)=>void}){return <div className="grid" style={{gap:16}}><div className="grid stats"><Stat label="Sales Hari Ini" value={rupiah(18450000)} trend="+18.6% vs kemarin"/><Stat label="Orders" value="128" trend="+12.4% volume"/><Stat label="Average Check" value={rupiah(144140)} trend="+6.8%"/><Stat label="Table Turnover" value="3.7x" trend="+0.4x"/></div><div className="grid layout2"><div className="card glass"><div className="split"><div><h2>Sales Performance</h2><p className="muted">7 hari terakhir • Gross sales</p></div><span className="badge green">LIVE</span></div><div style={{height:220,display:"flex",alignItems:"end",gap:10,padding:"20px 0"}}>{[52,68,45,81,72,92,78,98,85,74,91,100,88,96].map((v,i)=><div key={i} style={{flex:1,height:`${v}%`,borderRadius:"8px 8px 2px 2px",background:"linear-gradient(180deg,#65dfff,#247fe8)",opacity:.55+i/30}}/>)}</div><div className="split"><span className="muted">Mon</span><span className="muted">Sun</span></div></div><div className="card glass"><h2>Live Operations</h2><div className="grid" style={{gap:10}}><Live label="New orders" value="3" tone="amber"/><Live label="Cooking" value="7" tone="green"/><Live label="Ready to serve" value="4" tone="green"/><Live label="Occupied tables" value="12 / 20" tone="amber"/><Live label="Reservations" value="9 tonight" tone="green"/></div></div></div><div className="grid layout3"><div className="card glass"><h3>Recent Orders</h3>{orders.slice(0,4).map(o=><div className="cartLine" key={o.id}><div><b>{o.id}</b><div className="muted">{o.table} • {o.customer}</div></div><div style={{textAlign:"right"}}><b>{rupiah(o.total)}</b><br/><span className="badge">{o.status}</span></div></div>)}<button className="btn" style={{marginTop:12}} onClick={()=>setPage("Pesanan")}>View all</button></div><div className="card glass"><h3>Top Menu</h3>{[["Beef Tenderloin",92],["Truffle Pasta",78],["Signature Mocktail",71],["Salmon Miso",64]].map(([n,v])=><div key={String(n)} style={{marginBottom:14}}><div className="split"><span>{n}</span><b>{v}%</b></div><div className="bar" style={{marginTop:7}}><i style={{width:`${v}%`}}/></div>)}</div><div className="card glass"><h3>Manager Alerts</h3><p className="muted">2 menu stock berada di bawah par level.</p><p className="muted">1 reservation membutuhkan konfirmasi deposit.</p><p className="muted">3 order QR belum dikonfirmasi kasir.</p><button className="btn primary" onClick={()=>setPage("Inventory")}>Review alerts</button></div></div></div>}

function Stat({label,value,trend}:{label:string;value:string;trend:string}){return <div className="stat glass"><div className="label">{label}</div><div className="value">{value}</div><div className="trend">{trend}</div></div>}
function Live({label,value,tone}:{label:string;value:string;tone:"green"|"amber"}){return <div className="split" style={{padding:"9px 0",borderBottom:"1px solid var(--line)"}}><span>{label}</span><span className={`badge ${tone}`}>{value}</span></div>}

function PosPage({filtered,categories,cat,setCat,query,setQuery,add,cart,setCart,total,completeSale}:any){return <div className="grid pos"><div><div className="card glass"><div className="split"><div><h2>Point of Sale</h2><p className="muted">Dine-in • Takeaway • Delivery • QR</p></div><span className="badge green">Register #01</span></div><input className="search" placeholder="Cari menu..." value={query} onChange={e=>setQuery(e.target.value)}/><div className="catRow" style={{marginTop:10}}>{categories.map((c:string)=><button key={c} className={`btn cat ${cat===c?"primary":""}`} onClick={()=>setCat(c)}>{c}</button>)}</div></div><div className="grid menuGrid" style={{marginTop:14}}>{filtered.map((m:Menu)=><div className="card glass menuItem" key={m.id}><div className="menuIcon">{m.emoji}</div><h3>{m.name}</h3><div className="split"><span className="muted">{m.category}</span><span className="price">{rupiah(m.price)}</span></div><button className="btn primary" style={{width:"100%",marginTop:12}} onClick={()=>add(m)}>Add to order</button></div>)}</div></div><aside className="card glass cart"><div className="split"><h2>Current Order</h2><span className="badge">{cart.reduce((s:any,x:any)=>s+x.qty,0)} items</span></div>{!cart.length?<div className="empty">Pilih menu untuk memulai transaksi.</div>:cart.map((x:any)=><div className="cartLine" key={x.item.id}><div><b>{x.item.name}</b><div className="muted">{rupiah(x.item.price)}</div></div><div><div className="qty"><button onClick={()=>setCart((c:any)=>c.map((i:any)=>i.item.id===x.item.id?{...i,qty:i.qty-1}:i).filter((i:any)=>i.qty>0))}>−</button><b>{x.qty}</b><button onClick={()=>setCart((c:any)=>c.map((i:any)=>i.item.id===x.item.id?{...i,qty:i.qty+1}:i))}>+</button></div></div></div>)}<div style={{marginTop:18}}><div className="split"><span>Subtotal</span><b>{rupiah(total)}</b></div><div className="split muted" style={{marginTop:8}}><span>Service 5%</span><span>{rupiah(total*.05)}</span></div><div className="split" style={{marginTop:12}}><span className="total">Total</span><span className="total">{rupiah(total*1.05)}</span></div><button className="btn success" style={{width:"100%",marginTop:15}} onClick={completeSale}>Charge & Complete</button><button className="btn" style={{width:"100%",marginTop:8}} onClick={()=>setCart([])}>Clear</button></div></aside></div>}

function OrdersPage({orders,updateStatus}:{orders:Order[];updateStatus:(id:string,s:Order["status"])=>void}){return <div className="card glass"><div className="split"><div><h2>Order Management</h2><p className="muted">Omnichannel order queue • POS / QR / WhatsApp</p></div><button className="btn primary">+ Manual Order</button></div><div className="tableWrap"><table className="data"><thead><tr><th>Order</th><th>Guest</th><th>Table</th><th>Channel</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.id}</b><br/><span className="muted">{o.time}</span></td><td>{o.customer}</td><td>{o.table}</td><td><span className="badge">{o.channel}</span></td><td>{rupiah(o.total)}</td><td><span className={`badge ${o.status==="PAID"?"green":o.status==="NEW"?"amber":o.status==="CANCELLED"?"red":""}`}>{o.status}</span></td><td><select className="input" style={{width:130,margin:0}} value={o.status} onChange={e=>updateStatus(o.id,e.target.value as Order["status"])}><option>NEW</option><option>CONFIRMED</option><option>COOKING</option><option>READY</option><option>SERVED</option><option>PAID</option><option>CANCELLED</option></select></td></tr>)}</tbody></table></div></div>}

function KitchenPage({orders,updateStatus}:{orders:Order[];updateStatus:(id:string,s:Order["status"])=>void}){const cols=["NEW","CONFIRMED","COOKING","READY"] as const;return <div className="grid layout3">{cols.map(c=><div className="card glass" key={c}><div className="split"><h2>{c}</h2><span className="badge">{orders.filter(o=>o.status===c).length}</span></div>{orders.filter(o=>o.status===c).map(o=><div className="card" style={{padding:13,marginBottom:10,background:"rgba(255,255,255,.035)"}} key={o.id}><div className="split"><b>{o.id}</b><span className="muted">{o.time}</span></div><p className="muted">{o.table} • {o.customer}</p>{o.items.map(i=><div key={i} style={{padding:"5px 0"}}>• {i}</div>)}<button className="btn primary" style={{marginTop:8,width:"100%"}} onClick={()=>updateStatus(o.id,c==="NEW"?"CONFIRMED":c==="CONFIRMED"?"COOKING":"READY")}>{c==="READY"?"Serve":"Next status"}</button></div>)}</div>)}</div>}

function TablesPage(){return <div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))"}}>{tables.map(t=><div className="card glass" key={t.id}><div className="split"><h2>{t.id}</h2><span className={`badge ${t.status==="AVAILABLE"?"green":t.status==="RESERVED"?"amber":"red"}`}>{t.status}</span></div><p className="muted">{t.seats} seats</p><button className="btn" style={{width:"100%"}}>Open table</button></div>)}</div>}

function SimplePage({title,icon,desc,rows}:{title:string;icon:React.ReactNode;desc:string;rows:string[]}){return <div className="card glass"><div style={{display:"flex",gap:12,alignItems:"center"}}><div className="menuIcon">{icon}</div><div><h2>{title}</h2><p className="muted">{desc}</p></div></div><div className="grid" style={{marginTop:15}}>{rows.map(r=><div className="card" key={r} style={{background:"rgba(255,255,255,.035)"}}><div className="split"><span>{r}</span><ChevronRight size={16}/></div></div>)}</div></div>}

function MenuPage(){return <div className="card glass"><div className="split"><div><h2>Menu Engineering</h2><p className="muted">Recipe, modifier, pricing, availability dan profitability.</p></div><button className="btn primary">+ Add menu</button></div><div className="tableWrap"><table className="data"><thead><tr><th>Menu</th><th>Category</th><th>Price</th><th>Cost</th><th>Margin</th><th>Stock</th><th>Status</th></tr></thead><tbody>{menus.map(m=><tr key={m.id}><td>{m.emoji} <b>{m.name}</b></td><td>{m.category}</td><td>{rupiah(m.price)}</td><td>{rupiah(m.cost)}</td><td>{Math.round((1-m.cost/m.price)*100)}%</td><td>{m.stock}</td><td><span className={`badge ${m.active?"green":"red"}`}>{m.active?"ACTIVE":"OFF"}</span></td></tr>)}</tbody></table></div></div>}

function InventoryPage(){return <div className="grid layout2"><div className="card glass"><h2>Stock Control</h2><p className="muted">Par level, recipe deduction, purchase & wastage.</p>{[["Beef Tenderloin",18,25],["Salmon",12,20],["Truffle",4,10],["Coffee Beans",32,15],["Fresh Milk",8,20]].map(([n,s,p])=><div key={String(n)} style={{padding:"13px 0",borderBottom:"1px solid var(--line)"}}><div className="split"><span>{n}</span><b>{s} unit</b></div><div className="bar" style={{marginTop:8}}><i style={{width:`${Math.min(100,(Number(s)/Number(p))*100)}%`}}/></div></div>)}</div><div className="card glass"><h2>Purchase & Wastage</h2><button className="btn primary" style={{width:"100%"}}>+ Purchase Order</button><button className="btn" style={{width:"100%",marginTop:9}}>Record Wastage</button><div style={{marginTop:18}} className="muted">Last PO • PO-2409 • Rp8.420.000</div></div></div>}

function ReportsPage({orders}:{orders:Order[]}){return <div className="grid layout2"><div className="card glass"><h2>Executive Reports</h2><p className="muted">Sales, COGS, gross margin, payment mix dan staff performance.</p>{[["Gross Sales",rupiah(18450000)],["Discount",rupiah(320000)],["Tax & Service",rupiah(1420000)],["COGS",rupiah(6240000)],["Gross Profit",rupiah(13310000)]].map(x=><div className="split" style={{padding:"12px 0",borderBottom:"1px solid var(--line)"}} key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<button className="btn primary" style={{marginTop:14}}>Export PDF</button><button className="btn" style={{marginTop:14,marginLeft:8}}>Export Excel</button></div><div className="card glass"><h2>Payment Mix</h2>{[["Cash",32],["QRIS",41],["Debit/Credit",19],["E-Wallet",8]].map(([n,v])=><div style={{marginBottom:15}} key={String(n)}><div className="split"><span>{n}</span><b>{v}%</b></div><div className="bar" style={{marginTop:7}}><i style={{width:`${v}%`}}/></div>)}<p className="muted">Total orders analyzed: {orders.length} sample orders.</p></div></div>}

function OnlinePage(){const url=typeof window!=="undefined"?`${window.location.origin}/customer/kastriva/meja-01`:"https://your-domain.vercel.app/customer/kastriva/meja-01";return <div className="grid layout2"><div className="card glass"><div className="split"><div><h2>QR Ordering</h2><p className="muted">Per-table ordering, digital menu and WhatsApp handoff.</p></div><QrCode/></div><div className="qrBox" style={{marginTop:15}}><img src={`https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(url)}`} alt="QR meja 01"/></div><div className="qr" style={{marginTop:12}}>{url}</div><button className="btn primary" style={{marginTop:12}} onClick={()=>navigator.clipboard?.writeText(url)}>Copy URL</button></div><div className="card glass"><h2>Online Order Settings</h2>{["Accept QR orders","WhatsApp cashier handoff","Auto confirm low-risk orders","Show table number","Allow customer notes","Enable order cut-off"].map((x,i)=><label className="split" style={{padding:"12px 0",borderBottom:"1px solid var(--line)"}} key={x}><span>{x}</span><input type="checkbox" defaultChecked={i<5}/></label>)}</div></div>}

function SettingsPage(){return <div className="grid layout2"><div className="card glass"><h2>Store Profile</h2><div className="formGrid"><Field label="Business name" value="Kastriva Grand Dining"/><Field label="Branch" value="Jakarta • Senopati"/><Field label="Tax" value="11%"/><Field label="Service charge" value="5%"/><Field label="Currency" value="IDR"/><Field label="Timezone" value="Asia/Jakarta"/></div><button className="btn primary" style={{marginTop:15}}>Save settings</button></div><div className="card glass"><h2>Security & Integrations</h2>{["Cashier approval PIN","Role-based permissions","WhatsApp Business","QRIS / Payment Gateway","Cloud backup","Audit log"].map(x=><div className="split" style={{padding:"12px 0",borderBottom:"1px solid var(--line)"}} key={x}><span>{x}</span><span className="badge green">Configured</span></div>)}</div></div>}

function Field({label,value}:{label:string;value:string}){return <label className="label">{label}<input className="input" defaultValue={value}/></label>}