 "use client";
import {useMemo,useState} from "react";
import {menu,rupiah,MenuItem} from "../lib/data";
type CartItem=MenuItem&{qty:number};
export default function CustomerMenu({storeId,tableId}:{storeId:string;tableId:string}){
 const [cart,setCart]=useState<CartItem[]>([]); const [note,setNote]=useState(""); const [name,setName]=useState("");
 const add=(item:MenuItem)=>setCart(c=>{const x=c.find(i=>i.id===item.id);return x?c.map(i=>i.id===item.id?{...i,qty:i.qty+1}:i):[...c,{...item,qty:1}]});
 const change=(id:string,d:number)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+d}:i).filter(i=>i.qty>0));
 const total=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.qty,0),[cart]);
 const checkout=()=>{if(!cart.length)return alert("Keranjang masih kosong.");const lines=cart.map(i=>`• ${i.name} x${i.qty} = ${rupiah(i.price*i.qty)}`).join("\\n");const msg=`PESANAN BARU\\n\\nToko: ${storeId}\\nMeja: ${tableId}\\nNama: ${name||"-"}\\n\\n${lines}\\n\\nTOTAL: ${rupiah(total)}\\nCatatan: ${note||"-"}`;const phone=process.env.NEXT_PUBLIC_CASHIER_WHATSAPP||"";const url=phone?`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`:`https://wa.me/?text=${encodeURIComponent(msg)}`;window.open(url,"_blank")};
 return <main className="container"><div className="topbar"><div><h1>{process.env.NEXT_PUBLIC_STORE_NAME||"Kedai Saya"}</h1><div className="muted">Meja {tableId} • Pesan sendiri</div></div><span className="badge">{cart.reduce((s,i)=>s+i.qty,0)} item</span></div>
 <div className="grid menuGrid">{menu.map(i=><div className="card" key={i.id}><h3>{i.name}</h3><p className="muted">{i.description}</p><div className="row"><span className="price">{rupiah(i.price)}</span><button className="btn" onClick={()=>add(i)}>Tambah</button></div></div>)}</div>
 <div className="card sticky" style={{marginTop:18}}><h2>Keranjang</h2>{cart.length===0?<p className="muted">Belum ada menu.</p>:cart.map(i=><div className="orderItem row" key={i.id}><div><b>{i.name}</b><div>{rupiah(i.price*i.qty)}</div></div><div className="qty"><button onClick={()=>change(i.id,-1)}>−</button><b>{i.qty}</b><button onClick={()=>change(i.id,1)}>+</button></div></div>)}<div style={{marginTop:16}}><label>Nama pemesan<input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Opsional"/></label><label style={{display:"block",marginTop:10}}>Catatan<textarea className="input textarea" value={note} onChange={e=>setNote(e.target.value)} placeholder="Contoh: tidak pedas"/></label><div className="row" style={{marginTop:16}}><b>Total</b><b className="price">{rupiah(total)}</b></div><button className="btn whatsapp" style={{width:"100%",marginTop:12}} onClick={checkout}>Kirim Pesanan ke WhatsApp Kasir</button></div></div></main>
}